/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 简单的加法函数，供 Electron 主进程调用 */
export declare function add(a: number, b: number): number
/** 返回问候语，用于验证 addon 是否正常加载 */
export declare function hello(name: string): string
